name: Build
on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Erstelle JSON-Datei mit Wert
        run: |
          echo '{"version": "${{ github.run_number }}"}' > data.json

      - name: Lade Artefakt hoch
        uses: actions/upload-artifact@v4
        with:
          name: build-data
          path: data.json
