name: Build and Deploy Container App

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: cloudquickstartregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t acryok26zgypcrse.azurecr.io/sqlapp:${{ github.sha }}
        docker push acryok26zgypcrse.azurecr.io/sqlapp:${{ github.sha }}