name: Deploy Infrastructure by Bicep

on:
  workflow_dispatch:

jobs:
  deployResources:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
      - name: Deployment ResourceGroup
        run: |
          az deployment sub create \
            --location westeurope \
            --template-file ./main.bicep \
            --output json > deployment_output.json \
      - name: Upload deployment output
        uses: actions/upload-artifact@v4
        with: 
          name: deployment output-${{ github.run_number }}
          path: dist/


